import { NextAuthProvider } from "@/config/providers/NextAuthProvider";
import localFont from "next/font/local";

import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = localFont({
  src: "../shared/font/Quicksand-VariableFont_wght.ttf",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`min-h-screen bg-background ${font.className}`}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
